name       : gradio
version    : '7.2'
release    : 11
source     :
    - https://github.com/haecker-felix/Gradio/archive/v7.2.tar.gz : 5a85d7d4afb1424e46c935114b268e4a65de2629d60f48eccd75d67ff4b113d2
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A GTK3 app for finding and listening to internet radio stations
description: |
    A GTK3 app for finding and listening to internet radio stations
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
