name       : gradio
version    : '5.0'
release    : 2
source     :
    - https://github.com/haecker-felix/gradio/archive/v5.0.tar.gz : ed7edc9aed2019493237334ecbc23ab4e34ba9649f99a1e301f087ddcb40af69
license    : GPL-3.0
component  : multimedia.audio
summary    : A GTK3 app for finding and listening to internet radio stations
description: |
    A GTK3 app for finding and listening to internet radio stations
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
